export const INCREMENT = 'COUNT/INCREMENT';
export const DECREMENT = 'COUNT/DECREMENT';
export const INCREMENT_IF_ODD = 'COUNT/INCREMENT_IF_ODD';
export const INCREMENT_ASYNC = 'COUNT/INCREMENT_ASYNC';
